version: '3'

services:
  gorush:
    image: appleboy/gorush
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    environment:
      - GORUSH_CORE_QUEUE_NUM=512
